### ISSUE TITLE
Sherpa support for Nemo ctc models via torchscript

### ISSUE THREAD

**Issue by uni-manjunath-ke** [k2-fsa/sherpa#303]
Hi All,
Can we use Sherpa framework with Nemo ctc models via torchscript. If it is supported, could you please point me to appropriate links? If this is not supported, is it planned for future? And, if yes, any timelines for such support? @csukuangfj 
Thanks
Manjunath

**Comment by csukuangfj** [comment]
@uni-manjunath-ke 

Do you have torchscript models available? If yes,  could you upload it to https://huggingface.co/
and we can support that.

**Comment by uni-manjunath-ke** [comment]
I have ".nemo" models produced by finetuning of https://catalog.ngc.nvidia.com/orgs/nvidia/teams/nemo/models/stt_hi_conformer_ctc_medium

How to I generate torchscript models for this. I will also have ".pt" checkpoints. Is it what is needed?

Is it really required to upload it to https://huggingface.co/ to get such support. Because, I may not be allowed to upload here.

Thanks

**Comment by csukuangfj** [comment]
1. If you don't want to make the model public, we can tell you the changes that you need to make to support torchscript ctc models from nemo.

3. If you can make the model public (wherever you put, huggingface is a common place to put pre-trained models), we can make the changes and you can use it directly.

---

> How to I generate torchscript models for this

We need a torchscript model either exported by `torch.jit.trace()` or `torch.jit.script()`.

Sorry, I don't have experience about how to use nemo to obtain a torchscript model.

**Comment by uni-manjunath-ke** [comment]
Sure, Thanks a lot. Will checkout and get back to you.

**Comment by csukuangfj** [comment]
If you can provide a torchscript nemo ctc model, which does not need to be trained by yourself. Any publicly available torchscript nemo ctc model is fine.

**Comment by uni-manjunath-ke** [comment]
Ok Thanks. I will try to get such model and share with you. Pls give me some time.

**Comment by uni-manjunath-ke** [comment]
Hi @csukuangfj , I managed to convert ".nemo" to ".pt" torchscript file. However, when I tried to host it on sherpa framework, I get some errors. Could you please guide me on the changes that that I need to make to support torchscript ctc models on Sherpa.


The error stack trace is as below:
$sherpa/bin/offline_ctc_asr.py --nn-model /data/manju/tamil/exp/models/tamil_ctc_tl_dc_re_rs_tvs.pt --tokens /data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_tokenizer_v2/tokenizer_spe_bpe_v512_max_6_pad/vocab.txt kkkk.wav
2023-02-22 09:18:36,955 INFO [offline_ctc_asr.py:312] {'nn_model': '/data/manju/tamil/exp/models/tamil_ctc_tl_dc_re_rs_tvs.pt', 'tokens': '/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_tokenizer_v2/tokenizer_spe_bpe_v512_max_6_pad/vocab.txt', 'HLG': None, 'lm_scale': 1.0, 'modified': True, 'search_beam': 20.0, 'output_beam': 8.0, 'min_active_states': 30, 'max_active_states': 10000, 'use_gpu': False, 'normalize_samples': True, 'sound_files': ['kkkk.wav']}
[F] /mnt/efs/manju/if/tools/sherpa/sherpa/csrc/symbol-table.cc:49:sherpa::SymbolTable::SymbolTable(const string&) 2023-02-22 09:18:37.351 Check failed: is.eof() 


[ Stack-Trace: ]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/sherpa/lib/libsherpa_core.so(sherpa::GetStackTrace()+0x4b) [0x7f137ad5527b]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/sherpa/lib/libsherpa_core.so(sherpa::SymbolTable::SymbolTable(std::string const&)+0x18b0) [0x7f137ad58260]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/sherpa/lib/libsherpa_cpp_api.so(sherpa::OfflineRecognizerCtcImpl::OfflineRecognizerCtcImpl(sherpa::OfflineRecognizerConfig const&)+0x65) [0x7f137adbc325]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/sherpa/lib/libsherpa_cpp_api.so(sherpa::OfflineRecognizer::OfflineRecognizer(sherpa::OfflineRecognizerConfig const&)+0x158) [0x7f137adb5048]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/_sherpa.cpython-39-x86_64-linux-gnu.so(+0x1f166) [0x7f137adfb166]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/_sherpa.cpython-39-x86_64-linux-gnu.so(+0x45ea1) [0x7f137ae21ea1]
python3() [0x507f97]
python3(_PyObject_MakeTpCall+0x2ec) [0x4f0f1c]
python3() [0x505f43]
python3() [0x503312]
python3() [0x4f13d0]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/torchaudio/_torchaudio.so(+0x34685) [0x7f13a0a14685]
python3(_PyObject_MakeTpCall+0x2ec) [0x4f0f1c]
python3(_PyEval_EvalFrameDefault+0x5285) [0x4ed425]
python3() [0x4f8923]
python3(_PyEval_EvalFrameDefault+0x3d1) [0x4e8571]
python3() [0x4f8923]
python3(_PyEval_EvalFrameDefault+0x3d1) [0x4e8571]
python3() [0x4e729a]
python3(_PyEval_EvalCodeWithName+0x47) [0x4e6f27]
python3(PyEval_EvalCodeEx+0x39) [0x4e6ed9]
python3(PyEval_EvalCode+0x1b) [0x594f7b]
python3() [0x5c2457]
python3() [0x5be3b0]
python3() [0x456265]
python3(PyRun_SimpleFileExFlags+0x1a2) [0x5b81a2]
python3(Py_RunMain+0x37e) [0x5b570e]
python3(Py_BytesMain+0x39) [0x5890f9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f1431eb6083]
python3() [0x588fae]

Traceback (most recent call last):
  File "/mnt/efs/manju/if/tools/sherpa/sherpa/bin/offline_ctc_asr.py", line 359, in <module>
    main()
  File "/mnt/efs/manju/if/tools/sherpa/sherpa/bin/offline_ctc_asr.py", line 315, in main
    recognizer = create_recognizer(args)
  File "/mnt/efs/manju/if/tools/sherpa/sherpa/bin/offline_ctc_asr.py", line 305, in create_recognizer
    recognizer = sherpa.OfflineRecognizer(config)
RuntimeError: 
    Some bad things happened. Please read the above error messages and stack
    trace. If you are using Python, the following command may be helpful:

      gdb --args python /path/to/your/code.py

    (You can use `gdb` to debug the code. Please consider compiling
    a debug version of sherpa.).

    If you are unable to fix it, please open an issue at:

      https://github.com/k2-fsa/sherpa/issues/new
    
Thanks

**Comment by csukuangfj** [comment]
```
--tokens /data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_tokenizer_v2/tokenizer_spe_bpe_v512_max_6_pad/vocab.txt
```

What is the format of `vocab.txt`?

The expected format should like below
```
sym0 id0
sym1 id1
sym2 id2
```

e.g.
```
blk 0
a 1
b 2
c 3
```

**Comment by uni-manjunath-ke** [comment]
Thanks @csukuangfj 

I tried with tokenizer.vocab file generated from <Nemo_ROOT>/scripts/process_asr_text_tokenizer.py (https://github.com/NVIDIA/NeMo/blob/main/scripts/tokenizers/process_asr_text_tokenizer.py). 

The format of tokenizer.vocab is like this:
<unk>   0
<pad>   0
்க      -0
ங்க      -1
▁s      -2

But, I still get this error:
sherpa/bin/offline_ctc_asr.py --nn-model /data/manju/tamil/exp/models/tamil_ctc_tl_dc_re_rs_tvs.pt --tokens /data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_tokenizer_v2/tokenizer_spe_bpe_v512_max_6_pad/tokenizer.vocab kkkk.wav
2023-02-22 11:26:57,545 INFO [offline_ctc_asr.py:312] {'nn_model': '/data/manju/tamil/exp/models/tamil_ctc_tl_dc_re_rs_tvs.pt', 'tokens': '/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_tokenizer_v2/tokenizer_spe_bpe_v512_max_6_pad/tokenizer.vocab', 'HLG': None, 'lm_scale': 1.0, 'modified': True, 'search_beam': 20.0, 'output_beam': 8.0, 'min_active_states': 30, 'max_active_states': 10000, 'use_gpu': False, 'normalize_samples': True, 'sound_files': ['kkkk.wav']}
[F] /mnt/efs/manju/if/tools/sherpa/sherpa/csrc/symbol-table.cc:44:sherpa::SymbolTable::SymbolTable(const string&) 2023-02-22 11:26:58.010 Check failed: id2sym_.count(id) == 0 (1 vs. 0) Duplicated ID: 0


[ Stack-Trace: ]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/sherpa/lib/libsherpa_core.so(sherpa::GetStackTrace()+0x4b) [0x7f529559b27b]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/sherpa/lib/libsherpa_core.so(sherpa::SymbolTable::SymbolTable(std::string const&)+0x163c) [0x7f529559dfec]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/sherpa/lib/libsherpa_cpp_api.so(sherpa::OfflineRecognizerCtcImpl::OfflineRecognizerCtcImpl(sherpa::OfflineRecognizerConfig const&)+0x65) [0x7f5295602325]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/sherpa/lib/libsherpa_cpp_api.so(sherpa::OfflineRecognizer::OfflineRecognizer(sherpa::OfflineRecognizerConfig const&)+0x158) [0x7f52955fb048]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/_sherpa.cpython-39-x86_64-linux-gnu.so(+0x1f166) [0x7f5295641166]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/_sherpa.cpython-39-x86_64-linux-gnu.so(+0x45ea1) [0x7f5295667ea1]
python3() [0x507f97]
python3(_PyObject_MakeTpCall+0x2ec) [0x4f0f1c]
python3() [0x505f43]
python3() [0x503312]
python3() [0x4f13d0]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/torchaudio/_torchaudio.so(+0x34685) [0x7f52b9e5a685]
python3(_PyObject_MakeTpCall+0x2ec) [0x4f0f1c]
python3(_PyEval_EvalFrameDefault+0x5285) [0x4ed425]
python3() [0x4f8923]
python3(_PyEval_EvalFrameDefault+0x3d1) [0x4e8571]
python3() [0x4f8923]
python3(_PyEval_EvalFrameDefault+0x3d1) [0x4e8571]
python3() [0x4e729a]
python3(_PyEval_EvalCodeWithName+0x47) [0x4e6f27]
python3(PyEval_EvalCodeEx+0x39) [0x4e6ed9]
python3(PyEval_EvalCode+0x1b) [0x594f7b]
python3() [0x5c2457]
python3() [0x5be3b0]
python3() [0x456265]
python3(PyRun_SimpleFileExFlags+0x1a2) [0x5b81a2]
python3(Py_RunMain+0x37e) [0x5b570e]
python3(Py_BytesMain+0x39) [0x5890f9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f534b2fc083]
python3() [0x588fae]

Traceback (most recent call last):
  File "/mnt/efs/manju/if/tools/sherpa/sherpa/bin/offline_ctc_asr.py", line 359, in <module>
    main()
  File "/mnt/efs/manju/if/tools/sherpa/sherpa/bin/offline_ctc_asr.py", line 315, in main
    recognizer = create_recognizer(args)
  File "/mnt/efs/manju/if/tools/sherpa/sherpa/bin/offline_ctc_asr.py", line 305, in create_recognizer
    recognizer = sherpa.OfflineRecognizer(config)
RuntimeError: 
    Some bad things happened. Please read the above error messages and stack
    trace. If you are using Python, the following command may be helpful

**Comment by csukuangfj** [comment]
Left first solve the issues about tokens and then the issues about the models.

From the error log,
> [F] /mnt/efs/manju/if/tools/sherpa/sherpa/csrc/symbol-table.cc:44:sherpa::SymbolTable::SymbolTable(const string&) 2023-02-22 11:26:58.010 Check failed: id2sym_.count(id) == 0 (1 vs. 0) Duplicated ID: 0

And from your posted
```
The format of tokenizer.vocab is like this:
<unk> 0
<pad> 0
்க -0
ங்க -1
▁s -2
```

You see `<unk>` and `<pad>` both have ID 0. That is not allowed. Please fix it first.

**Comment by uni-manjunath-ke** [comment]
I fixed it, and my new file looks as below:
<unk> 0
<pad> 1
்க 2

But, I still end up getting below error: 
[ Stack-Trace: ]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/sherpa/lib/libsherpa_core.so(sherpa::GetStackTrace()+0x4b) [0x7fedd07a427b]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/sherpa/lib/libsherpa_core.so(sherpa::SymbolTable::SymbolTable(std::string const&)+0x18b0) [0x7fedd07a7260]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/sherpa/lib/libsherpa_cpp_api.so(sherpa::OfflineRecognizerCtcImpl::OfflineRecognizerCtcImpl(sherpa::OfflineRecognizerConfig const&)+0x65) [0x7fedd080b325]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/sherpa/lib/libsherpa_cpp_api.so(sherpa::OfflineRecognizer::OfflineRecognizer(sherpa::OfflineRecognizerConfig const&)+0x158) [0x7fedd0804048]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/_sherpa.cpython-39-x86_64-linux-gnu.so(+0x1f166) [0x7fedd084a166]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/k2_sherpa-1.1-py3.9-linux-x86_64.egg/_sherpa.cpython-39-x86_64-linux-gnu.so(+0x45ea1) [0x7fedd0870ea1]
python3() [0x507f97]
python3(_PyObject_MakeTpCall+0x2ec) [0x4f0f1c]
python3() [0x505f43]
python3() [0x503312]
python3() [0x4f13d0]
/home/manjunath/anaconda3/envs/ice/lib/python3.9/site-packages/torchaudio/_torchaudio.so(+0x34685) [0x7fedef05e685]
python3(_PyObject_MakeTpCall+0x2ec) [0x4f0f1c]
python3(_PyEval_EvalFrameDefault+0x5285) [0x4ed425]
python3() [0x4f8923]
python3(_PyEval_EvalFrameDefault+0x3d1) [0x4e8571]
python3() [0x4f8923]
python3(_PyEval_EvalFrameDefault+0x3d1) [0x4e8571]
python3() [0x4e729a]
python3(_PyEval_EvalCodeWithName+0x47) [0x4e6f27]
python3(PyEval_EvalCodeEx+0x39) [0x4e6ed9]
python3(PyEval_EvalCode+0x1b) [0x594f7b]
python3() [0x5c2457]
python3() [0x5be3b0]
python3() [0x456265]
python3(PyRun_SimpleFileExFlags+0x1a2) [0x5b81a2]
python3(Py_RunMain+0x37e) [0x5b570e]
python3(Py_BytesMain+0x39) [0x5890f9]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7fee80500083]
python3() [0x588fae]

**Comment by csukuangfj** [comment]
Now it comes to the hard part.

please refer to
https://github.com/k2-fsa/sherpa/pull/198/commits/0e2c259144502fba9ff5d0b566944fa4b8e550ee
for how we add support for CTC models exported from torchaudio's pre-trained wav2vec 2.0 models.

----

Basically, you need to do the following:

1. Create a header file like below
https://github.com/k2-fsa/sherpa/blob/master/sherpa/csrc/offline-wav2vec2-ctc-model.h

2. Create a cpp implementation file like below
https://github.com/k2-fsa/sherpa/blob/master/sherpa/csrc/offline-wav2vec2-ctc-model.h

3. Change
https://github.com/k2-fsa/sherpa/blob/master/sherpa/cpp_api/offline-recognizer-ctc-impl.h

Change the following code to add support for your own model:

https://github.com/k2-fsa/sherpa/blob/92e3965cf1c00bbff31669f5d566d4e76500bc7f/sherpa/cpp_api/offline-recognizer-ctc-impl.h#L68-L89

**Comment by csukuangfj** [comment]
@uni-manjunath-ke 

Thanks! 

One more thing: Could you provide a python script to show how to use this model?

1. What is the signature of the forward method of the mode? That is, what are the inputs and outputs?  
2. What is the last layer of the model, e.g., nn.Linear, nn.Softmax, or nn.LogSoftmax ?
3. What are the feature extraction options of this model?  (You don't need to provide feature extraction code for the demo python script)

----

I will find some time to support it this weekend.

**Comment by uni-manjunath-ke** [comment]
Sure, Thanks @csukuangfj 
I have got this model by finetuning stt-hi-conformer-ctc-medium pretrained nemo model using the config file available at https://github.com/NVIDIA/NeMo/blob/main/examples/asr/conf/conformer/conformer_ctc_bpe.yaml
The encoder section in the config file contains the required data as below:  
encoder:
    _target_: nemo.collections.asr.modules.ConformerEncoder
    feat_in: ${model.preprocessor.features}
    feat_out: -1 # you may set it if you need different output size other than the default d_model
    n_layers: 18 # total no of layers
    d_model: 512 #--> o/p layer dimesion

The code-snippet for finetuning using Nemo pretrained models is as below:

import nemo
import nemo.collections.asr as nemo_asr
from pytorch_lightning.strategies import DDPStrategy
from jiwer import wer ##  libarry to compute WER
from statistics import mean  ## Used to compute mean WER
import pandas as pd #for IO
# for wav file resampling & segmentation
from scipy.io import wavfile
## to create directory if not exists
from pathlib import Path
import pytorch_lightning as pl
from omegaconf import DictConfig

basePath='/<home_user>/hindi/'

try:
    from ruamel.yaml import YAML
except ModuleNotFoundError:
    from ruamel_yaml import YAML
config_path = basePath + '/exp/config/hindi_custom_conformer_ctc_bpe.yaml'
yaml = YAML(typ='safe')
with open(config_path) as f:
    params = yaml.load(f)

conf_ctc_model = nemo_asr.models.EncDecCTCModelBPE.from_pretrained(model_name="stt_hi_conformer_ctc_medium")

tokenDir = basePath + '/exp/tokenizers/tokenizer_dc_tvs_hdc_v3/tokenizer_spe_bpe_v512_pad/'
conf_ctc_model.change_vocabulary(new_tokenizer_dir=tokenDir, new_tokenizer_type="bpe")
#### tokenizer building ---
# python /data/manju/hindi/scripts/process_asr_text_tokenizer.py   --manifest="/data/manju/hindi/exp/lists/train_hindi_dc_manifest.json"   
# --data_root="/data/manju/hindi/exp/tokenizer/"   --vocab_size=200   --tokenizer="spe"   --spe_type="bpe"  --spe_pad --log

train_manifest = basePath + '/exp/all_lists/lists/train_hindi_dc_TVS_HDC_manifest.json_small'
test_manifest = basePath + '/exp/all_lists/lists/test_hindi_dc_manifest.json_small'
valid_manifest = basePath + '/exp/all_lists/lists/valid_hindi_dc_TVS_HDC_manifest.json_small'

params['model']['train_ds']['manifest_filepath'] = train_manifest
params['model']['test_ds']['manifest_filepath'] = test_manifest
params['model']['validation_ds']['manifest_filepath'] = valid_manifest

# Point to the data we'll use for fine-tuning as the training set
conf_ctc_model.setup_training_data(train_data_config=params['model']['train_ds'])
# Point to the new validation data for fine-tuning
conf_ctc_model.setup_validation_data(val_data_config=params['model']['validation_ds'])
conf_ctc_model.setup_test_data(test_data_config=params['model']['test_ds'])

# And now we can create a PyTorch Lightning trainer and call `fit` again.
modelSaveName = basePath + '/exp/models/hindi_tl_demo.nemo'
rootDir = basePath + '/exp/logs/'

trainer = pl.Trainer(strategy=DDPStrategy(find_unused_parameters=False), 
                     accelerator='gpu',  
                     devices=[2], 
                     auto_lr_find = True, 
                     auto_scale_batch_size = True, 
                     val_check_interval = 0.25, 	
                     default_root_dir = rootDir,                     
                     max_epochs=3
                     )

trainer.fit(conf_ctc_model)
conf_ctc_model.save_to(modelSaveName)


Thanks

**Comment by uni-manjunath-ke** [comment]
Hi @csukuangfj,
 
 Please let us know, if there is any update on this? Thanks

**Comment by csukuangfj** [comment]
> Hi @csukuangfj,
> 
> Please let us know, if there is any update on this? Thanks

@uni-manjunath-ke 

Please have a look at https://github.com/k2-fsa/sherpa/pull/332

**Comment by uni-manjunath-ke** [comment]
Hi @csukuangfj, Thanks a lot.
I tried using this feature. Basically, it works fine if I use the command and wav files mentioned at https://github.com/k2-fsa/sherpa/pull/332 . 
But, If I change the wave file to my own wave file, then it gives error as below. I am verifying on finetuned models, and keep you updated. Thanks


$ build/sherpa/bin/sherpa-offline --nn-model=../sherpa__notWorking/old/sherpa-nemo-ctc-en-citrinet-512/model.pt --tokens=../sherpa__notWorking/old/sherpa-nemo-ctc-en-citrinet-512/tokens.txt   --use-gpu=false --modified=false   --nemo-normalize=per_feature ./re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav 
[I] /mnt/efs/manju/if/tools/sherpa/sherpa/csrc/parse-options.cc:495:int sherpa::ParseOptions::Read(int, const char* const*) 2023-03-10 07:54:19.533 build/sherpa/bin/sherpa-offline --nn-model=../sherpa__notWorking/old/sherpa-nemo-ctc-en-citrinet-512/model.pt --tokens=../sherpa__notWorking/old/sherpa-nemo-ctc-en-citrinet-512/tokens.txt --use-gpu=false --modified=false --nemo-normalize=per_feature ./re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav 

[I] /mnt/efs/manju/if/tools/sherpa/sherpa/cpp_api/bin/offline-recognizer.cc:125:int main(int, char**) 2023-03-10 07:54:19.535 OfflineRecognizerConfig(ctc_decoder_config=OfflineCtcDecoderConfig(modified=False, hlg="", lm_scale=1, search_beam=20, output_beam=8, min_active_states=30, max_active_states=10000), feat_config=FeatureConfig(fbank_opts=FbankOptions(frame_opts=FrameExtractionOptions(samp_freq=16000, frame_shift_ms=10, frame_length_ms=25, dither=0, preemph_coeff=0.97, remove_dc_offset=True, window_type="povey", round_to_power_of_two=True, blackman_coeff=0.42, snip_edges=True, max_feature_vectors=-1), mel_opts=MelBanksOptions(num_bins=80, low_freq=20, high_freq=0, vtln_low=100, vtln_high=-500, debug_mel=False, htk_mode=False), use_energy=False, energy_floor=0, raw_energy=True, htk_compat=False, use_log_fbank=True, use_power=True, device="cpu"), normalize_samples=True, nemo_normalize="per_feature"), nn_model="../sherpa__notWorking/old/sherpa-nemo-ctc-en-citrinet-512/model.pt", tokens="../sherpa__notWorking/old/sherpa-nemo-ctc-en-citrinet-512/tokens.txt", use_gpu=False, decoding_method="greedy_search", num_active_paths=4)
[I] /mnt/efs/manju/if/tools/sherpa/sherpa/cpp_api/offline-recognizer-ctc-impl.h:172:void sherpa::OfflineRecognizerCtcImpl::WarmUp() 2023-03-10 07:54:20.864 WarmUp begins
[I] /mnt/efs/manju/if/tools/sherpa/sherpa/cpp_api/offline-recognizer-ctc-impl.h:185:void sherpa::OfflineRecognizerCtcImpl::WarmUp() 2023-03-10 07:54:21.294 WarmUp ended
[F] /mnt/efs/manju/if/tools/sherpa/sherpa/csrc/fbank-features.cc:34:std::pair<at::Tensor, float> sherpa::ReadWave(const string&, float) 2023-03-10 07:54:21.368 Failed to read ./re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav


[ Stack-Trace: ]
./build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_core.so(sherpa::GetStackTrace()+0x4b) [0x7f119370ad0b]
build/sherpa/bin/sherpa-offline(sherpa::Logger::~Logger()+0x62) [0x56497c87f852]
./build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_core.so(+0x299ad) [0x7f11936c49ad]
./build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_cpp_api.so(sherpa::OfflineStream::AcceptWaveFile(std::string const&)+0x42) [0x7f1193778002]
build/sherpa/bin/sherpa-offline(+0xae8a) [0x56497c877e8a]
/lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf3) [0x7f114b9a1083]
build/sherpa/bin/sherpa-offline(+0xba5e) [0x56497c878a5e]

Aborted (core dumped)

**Comment by csukuangfj** [comment]
> ./sherpa__notWorking/old/sherpa-nemo-ctc-en-citrinet-512/tokens.txt 

How did you generate `tokens.txt` and `models.pt`?

**Comment by uni-manjunath-ke** [comment]
(sherpa) manjunath@ip-10-40-6-153:/mnt/efs/manju/if/tools/sherpa$ soxi ./re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav

Input File     : './re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav'
Channels       : 1
Sample Rate    : 16000
Precision      : 25-bit
Duration       : 00:00:04.34 = 69440 samples ~ 325.5 CDDA sectors
File Size      : 278k
Bit Rate       : 512k
Sample Encoding: 32-bit Floating Point PCM

**Comment by csukuangfj** [comment]
From your output:
```
Sample Encoding: 32-bit Floating Point PCM
```

Please convert it to 16-bit PCM.

**Comment by uni-manjunath-ke** [comment]
Ok Thanks

**Comment by csukuangfj** [comment]
Does it work now?

**Comment by csukuangfj** [comment]
For simplicity, the code only deals with 16-bit PCM encoded WAVE files.

You can convert your input files manually outside of sherpa with tools like ffmpeg, sox, etc.

**Comment by uni-manjunath-ke** [comment]
Hi @csukuangfj , 
Looping @titu1994 also for any suggestions.
It is failing with custom models. 
1. I have converted '.nemo' to '.pt' file using  below commands:
conf_ctc_model = nemo_asr.models.EncDecCTCModelBPE.restore_from(restore_path=<.nemo FineTunedModelPath>)
conf_ctc_model.export(<path to save .pt file>)
 This uses https://github.com/NVIDIA/NeMo/blob/main/scripts/export.py, script I believe.
2. Then I have converted tokens.txt to have <blk> token with '0' in the begining, and remianing token starting from 1 to 512, as below:
<blk>   0
<unk>   1
்க      2
 
 $build/sherpa/bin/sherpa-offline --nn-model=/data/manju/tamil/exp/models/noPad_tamil_ctc_tl_dc_re_rs_tvs.pt --tokens=/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_no_pad_data_tokenizer_v4/tokenizer_spe_bpe_v512_max_6/tokenizer.vocab_sherpa   --use-gpu=false --modified=false --nemo-normalize=per_feature ./16pcm_re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav 
[I] /mnt/efs/manju/if/tools/sherpa/sherpa/csrc/parse-options.cc:495:int sherpa::ParseOptions::Read(int, const char* const*) 2023-03-10 09:09:05.645 build/sherpa/bin/sherpa-offline --nn-model=/data/manju/tamil/exp/models/noPad_tamil_ctc_tl_dc_re_rs_tvs.pt --tokens=/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_no_pad_data_tokenizer_v4/tokenizer_spe_bpe_v512_max_6/tokenizer.vocab_sherpa --use-gpu=false --modified=false --nemo-normalize=per_feature ./16pcm_re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav 

[I] /mnt/efs/manju/if/tools/sherpa/sherpa/cpp_api/bin/offline-recognizer.cc:125:int main(int, char**) 2023-03-10 09:09:05.645 OfflineRecognizerConfig(ctc_decoder_config=OfflineCtcDecoderConfig(modified=False, hlg="", lm_scale=1, search_beam=20, output_beam=8, min_active_states=30, max_active_states=10000), feat_config=FeatureConfig(fbank_opts=FbankOptions(frame_opts=FrameExtractionOptions(samp_freq=16000, frame_shift_ms=10, frame_length_ms=25, dither=0, preemph_coeff=0.97, remove_dc_offset=True, window_type="povey", round_to_power_of_two=True, blackman_coeff=0.42, snip_edges=True, max_feature_vectors=-1), mel_opts=MelBanksOptions(num_bins=80, low_freq=20, high_freq=0, vtln_low=100, vtln_high=-500, debug_mel=False, htk_mode=False), use_energy=False, energy_floor=0, raw_energy=True, htk_compat=False, use_log_fbank=True, use_power=True, device="cpu"), normalize_samples=True, nemo_normalize="per_feature"), nn_model="/data/manju/tamil/exp/models/noPad_tamil_ctc_tl_dc_re_rs_tvs.pt", tokens="/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_no_pad_data_tokenizer_v4/tokenizer_spe_bpe_v512_max_6/tokenizer.vocab_sherpa", use_gpu=False, decoding_method="greedy_search", num_active_paths=4)
[I] /mnt/efs/manju/if/tools/sherpa/sherpa/cpp_api/offline-recognizer-ctc-impl.h:172:void sherpa::OfflineRecognizerCtcImpl::WarmUp() 2023-03-10 09:09:06.729 WarmUp begins
Aborted (core dumped)

Thanks

**Comment by csukuangfj** [comment]
@uni-manjunath-ke 

Could you use the code in
https://github.com/k2-fsa/sherpa/pull/332#issuecomment-1463507956
to test your model with torchscript to see if it works correctly before using sherpa.

**Comment by csukuangfj** [comment]
> RuntimeError: stft input and window must be on the same device but got self on cpu and window on cuda:0

Are you using GPU?

Is your model on GPU but your features are on CPU?

**Comment by uni-manjunath-ke** [comment]
> 
> Could you use the code in [#332 (comment)](https://github.com/k2-fsa/sherpa/pull/332#issuecomment-1463507956) to test your model with torchscript to see if it works correctly before using sherpa.

Hi @csukuangfj ,
I executed this code, and found that the results are similar to what have posted at [#332 (comment)](https://github.com/k2-fsa/sherpa/pull/332#issuecomment-1463507956)

Results obtained are:
print('samples', samples.shape, sample_rate)
features torch.Size([1, 80, 435]) tensor([435], device='cuda:0')
torch.Size([1, 109, 513])

**Comment by csukuangfj** [comment]
Are you using a conformer ctc model?

Your subsampling factor is 435 / 109 = 4.

I need to change the code. please wait a minute.

**Comment by uni-manjunath-ke** [comment]
Ya, I have used conformer ctc model.


> Are you using a conformer ctc model?
Ya, I have used conformer ctc model.
> Your subsampling factor is 435 / 109 = 4.
> 
> I need to change the code. please wait a minute.
Ok, Thanks

**Comment by csukuangfj** [comment]
@uni-manjunath-ke 

I has been fixed in https://github.com/k2-fsa/sherpa/pull/335

Please update your sherpa to the latest master and recompile.

**Comment by uni-manjunath-ke** [comment]
Ok Thanks a lot

**Comment by uni-manjunath-ke** [comment]
Hi @csukuangfj , I still get the same error after installing from latest master (git clone https://github.com/k2-fsa/sherpa.git).

sherpa$  build/sherpa/bin/sherpa-offline --nn-model=/data/manju/tamil/exp/models/noPad_tamil_ctc_tl_dc_re_rs_tvs.pt --tokens=/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_no_pad_data_tokenizer_v4/tokenizer_spe_bpe_v512_max_6/tokenizer.vocab_sherpa --use-gpu=false --modified=false --nemo-normalize=per_feature ./16pcm_re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav 
[I] /mnt/efs/manju/if/tools/sherpa/sherpa/csrc/parse-options.cc:495:int sherpa::ParseOptions::Read(int, const char* const*) 2023-03-10 13:07:24.965 build/sherpa/bin/sherpa-offline --nn-model=/data/manju/tamil/exp/models/noPad_tamil_ctc_tl_dc_re_rs_tvs.pt --tokens=/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_no_pad_data_tokenizer_v4/tokenizer_spe_bpe_v512_max_6/tokenizer.vocab_sherpa --use-gpu=false --modified=false --nemo-normalize=per_feature ./16pcm_re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav 

[I] /mnt/efs/manju/if/tools/sherpa/sherpa/cpp_api/bin/offline-recognizer.cc:125:int main(int, char**) 2023-03-10 13:07:24.965 OfflineRecognizerConfig(ctc_decoder_config=OfflineCtcDecoderConfig(modified=False, hlg="", lm_scale=1, search_beam=20, output_beam=8, min_active_states=30, max_active_states=10000), feat_config=FeatureConfig(fbank_opts=FbankOptions(frame_opts=FrameExtractionOptions(samp_freq=16000, frame_shift_ms=10, frame_length_ms=25, dither=0, preemph_coeff=0.97, remove_dc_offset=True, window_type="povey", round_to_power_of_two=True, blackman_coeff=0.42, snip_edges=True, max_feature_vectors=-1), mel_opts=MelBanksOptions(num_bins=80, low_freq=20, high_freq=0, vtln_low=100, vtln_high=-500, debug_mel=False, htk_mode=False), use_energy=False, energy_floor=0, raw_energy=True, htk_compat=False, use_log_fbank=True, use_power=True, device="cpu"), normalize_samples=True, nemo_normalize="per_feature"), nn_model="/data/manju/tamil/exp/models/noPad_tamil_ctc_tl_dc_re_rs_tvs.pt", tokens="/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_no_pad_data_tokenizer_v4/tokenizer_spe_bpe_v512_max_6/tokenizer.vocab_sherpa", use_gpu=False, decoding_method="greedy_search", num_active_paths=4)
[I] /mnt/efs/manju/if/tools/sherpa/sherpa/cpp_api/offline-recognizer-ctc-impl.h:182:void sherpa::OfflineRecognizerCtcImpl::WarmUp() 2023-03-10 13:07:26.130 WarmUp begins
Aborted (core dumped)

**Comment by csukuangfj** [comment]
could you build a debug version of sherpa?
```
cd build
rm CMakeCache.txt
cmake -DCMAKE_BUILD_TYPE=Debug ..
make -j 6
```

and then use
```
gdb --args  \
 build/sherpa/bin/sherpa-offline --nn-model=/data/manju/tamil/exp/models/noPad_tamil_ctc_tl_dc_re_rs_tvs.pt --tokens=/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_no_pad_data_tokenizer_v4/tokenizer_spe_bpe_v512_max_6/tokenizer.vocab_sherpa --use-gpu=false --modified=false --nemo-normalize=per_feature ./16pcm_re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav

(gdb) run
```

When it crashes, please use
```
(gdb) backtrace
```

and post the output of  the`backtrace`.

**Comment by csukuangfj** [comment]
By the way, how large is your vocabulary? If it's several thousand, please set the option: --modified=true

**Comment by titu1994** [comment]
Conformer vocab is usually (128-1024)+1. 
Citrinet is usually (256-1024)+1.
Asian languages use character encoder so roughly 5000 ish tokens. 

Added some comment to note that Citrinet has 8x stride not 16x

**Comment by uni-manjunath-ke** [comment]
> run

Hi @csukuangfj , Thanks. Here is the output of gdb debugging. Meanwhile, as I understand Nvidia team is working on fixing torchscript export issues at https://github.com/k2-fsa/sherpa/issues/303 , Should wait for them to get back? Thanks

(sherpa) manjunath@ip-10-40-6-153:/mnt/efs/manju/if/tools/sherpa$ gdb --args   build/sherpa/bin/sherpa-offline --nn-model=/data/manju/tamil/exp/models/noPad_tamil_ctc_tl_dc_re_rs_tvs.pt --tokens=/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_no_pad_data_tokenizer_v4/tokenizer_spe_bpe_v512_max_6/tokenizer.vocab_sherpa --use-gpu=false --modified=false --nemo-normalize=per_feature ../16pcm_re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04.1) 9.2
Copyright (C) 2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from build/sherpa/bin/sherpa-offline...
(No debugging symbols found in build/sherpa/bin/sherpa-offline)
(gdb) run
Starting program: /mnt/efs/manju/if/tools/sherpa/build/sherpa/bin/sherpa-offline --nn-model=/data/manju/tamil/exp/models/noPad_tamil_ctc_tl_dc_re_rs_tvs.pt --tokens=/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_no_pad_data_tokenizer_v4/tokenizer_spe_bpe_v512_max_6/tokenizer.vocab_sherpa --use-gpu=false --modified=false --nemo-normalize=per_feature ../16pcm_re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fff63d11000 (LWP 2520357)]
[New Thread 0x7fff63510000 (LWP 2520358)]
[New Thread 0x7fff62d0f000 (LWP 2520359)]
[New Thread 0x7fff6250e000 (LWP 2520360)]
[New Thread 0x7fff61d0d000 (LWP 2520361)]
[New Thread 0x7fff6150c000 (LWP 2520362)]
[New Thread 0x7fff60d0b000 (LWP 2520363)]
[New Thread 0x7fff6050a000 (LWP 2520364)]
[New Thread 0x7fff5fd09000 (LWP 2520365)]
[New Thread 0x7fff5f508000 (LWP 2520366)]
[New Thread 0x7fff5ed07000 (LWP 2520367)]
[New Thread 0x7fff5e506000 (LWP 2520368)]
[New Thread 0x7fff5dd05000 (LWP 2520369)]
[New Thread 0x7fff5d504000 (LWP 2520370)]
[New Thread 0x7fff5cd03000 (LWP 2520371)]
[New Thread 0x7fff5c502000 (LWP 2520372)]
[New Thread 0x7fff5bd01000 (LWP 2520373)]
[New Thread 0x7fff5b500000 (LWP 2520374)]
[New Thread 0x7fff5acff000 (LWP 2520375)]
[New Thread 0x7fff5a4fe000 (LWP 2520376)]
[New Thread 0x7fff59cfd000 (LWP 2520377)]
[New Thread 0x7fff594fc000 (LWP 2520378)]
[New Thread 0x7fff58cfb000 (LWP 2520379)]
[New Thread 0x7fff584fa000 (LWP 2520380)]
[New Thread 0x7fff57cf9000 (LWP 2520381)]
[New Thread 0x7fff574f8000 (LWP 2520382)]
[New Thread 0x7fff56cf7000 (LWP 2520383)]
[New Thread 0x7fff564f6000 (LWP 2520384)]
[New Thread 0x7fff55cf5000 (LWP 2520385)]
[New Thread 0x7fff554f4000 (LWP 2520386)]
[New Thread 0x7fff54cf3000 (LWP 2520387)]
[Thread 0x7fff554f4000 (LWP 2520386) exited]
[Thread 0x7fff564f6000 (LWP 2520384) exited]
[Thread 0x7fff574f8000 (LWP 2520382) exited]
[Thread 0x7fff57cf9000 (LWP 2520381) exited]
[Thread 0x7fff58cfb000 (LWP 2520379) exited]
[Thread 0x7fff594fc000 (LWP 2520378) exited]
[Thread 0x7fff5bd01000 (LWP 2520373) exited]
[Thread 0x7fff55cf5000 (LWP 2520385) exited]
[Thread 0x7fff59cfd000 (LWP 2520377) exited]
[Thread 0x7fff5a4fe000 (LWP 2520376) exited]
[Thread 0x7fff5acff000 (LWP 2520375) exited]
[Thread 0x7fff56cf7000 (LWP 2520383) exited]
[Thread 0x7fff584fa000 (LWP 2520380) exited]
[Thread 0x7fff54cf3000 (LWP 2520387) exited]
[Thread 0x7fff5b500000 (LWP 2520374) exited]
[Thread 0x7fff5c502000 (LWP 2520372) exited]
[Thread 0x7fff5cd03000 (LWP 2520371) exited]
[Thread 0x7fff5d504000 (LWP 2520370) exited]
[Thread 0x7fff5dd05000 (LWP 2520369) exited]
[Thread 0x7fff5e506000 (LWP 2520368) exited]
[Thread 0x7fff5ed07000 (LWP 2520367) exited]
[Thread 0x7fff5f508000 (LWP 2520366) exited]
[Thread 0x7fff5fd09000 (LWP 2520365) exited]
[Thread 0x7fff6050a000 (LWP 2520364) exited]
[Thread 0x7fff60d0b000 (LWP 2520363) exited]
[Thread 0x7fff6150c000 (LWP 2520362) exited]
[Thread 0x7fff61d0d000 (LWP 2520361) exited]
[Thread 0x7fff6250e000 (LWP 2520360) exited]
[Thread 0x7fff62d0f000 (LWP 2520359) exited]
[Thread 0x7fff63510000 (LWP 2520358) exited]
[Thread 0x7fff63d11000 (LWP 2520357) exited]
[I] /mnt/efs/manju/if/tools/sherpa/sherpa/csrc/parse-options.cc:495:int sherpa::ParseOptions::Read(int, const char* const*) 2023-03-13 07:30:49.461 /mnt/efs/manju/if/tools/sherpa/build/sherpa/bin/sherpa-offline --nn-model=/data/manju/tamil/exp/models/noPad_tamil_ctc_tl_dc_re_rs_tvs.pt --tokens=/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_no_pad_data_tokenizer_v4/tokenizer_spe_bpe_v512_max_6/tokenizer.vocab_sherpa --use-gpu=false --modified=false --nemo-normalize=per_feature ../16pcm_re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav 

[I] /mnt/efs/manju/if/tools/sherpa/sherpa/cpp_api/bin/offline-recognizer.cc:125:int main(int, char**) 2023-03-13 07:30:49.461 OfflineRecognizerConfig(ctc_decoder_config=OfflineCtcDecoderConfig(modified=False, hlg="", lm_scale=1, search_beam=20, output_beam=8, min_active_states=30, max_active_states=10000), feat_config=FeatureConfig(fbank_opts=FbankOptions(frame_opts=FrameExtractionOptions(samp_freq=16000, frame_shift_ms=10, frame_length_ms=25, dither=0, preemph_coeff=0.97, remove_dc_offset=True, window_type="povey", round_to_power_of_two=True, blackman_coeff=0.42, snip_edges=True, max_feature_vectors=-1), mel_opts=MelBanksOptions(num_bins=80, low_freq=20, high_freq=0, vtln_low=100, vtln_high=-500, debug_mel=False, htk_mode=False), use_energy=False, energy_floor=0, raw_energy=True, htk_compat=False, use_log_fbank=True, use_power=True, device="cpu"), normalize_samples=True, nemo_normalize="per_feature"), nn_model="/data/manju/tamil/exp/models/noPad_tamil_ctc_tl_dc_re_rs_tvs.pt", tokens="/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_no_pad_data_tokenizer_v4/tokenizer_spe_bpe_v512_max_6/tokenizer.vocab_sherpa", use_gpu=False, decoding_method="greedy_search", num_active_paths=4)
[I] /mnt/efs/manju/if/tools/sherpa/sherpa/cpp_api/offline-recognizer-ctc-impl.h:182:void sherpa::OfflineRecognizerCtcImpl::WarmUp() 2023-03-13 07:30:50.666 WarmUp begins
--Type <RET> for more, q to quit, c to continue without paging--

Thread 1 "sherpa-offline" received signal SIGABRT, Aborted.
__GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
50        return ret;
(gdb)

**Comment by csukuangfj** [comment]
> could you build a debug version of sherpa?
> 
> ```
> 
> cd build
> 
> rm CMakeCache.txt
> 
> cmake -DCMAKE_BUILD_TYPE=Debug ..
> 
> make -j 6
> 
> ```
> 
> 
> 
> and then use
> 
> ```
> 
> gdb --args  \
> 
>  build/sherpa/bin/sherpa-offline --nn-model=/data/manju/tamil/exp/models/noPad_tamil_ctc_tl_dc_re_rs_tvs.pt --tokens=/data/manju/tamil/exp/tokenizers/dc_re_rs_tvs_no_pad_data_tokenizer_v4/tokenizer_spe_bpe_v512_max_6/tokenizer.vocab_sherpa --use-gpu=false --modified=false --nemo-normalize=per_feature ./16pcm_re_test__q_vNeC-nX4X0LWuORXDmp_l_0001.wav
> 
> 
> 
> (gdb) run
> 
> ```
> 
> 
> 
> When it crashes, please use
> 
> ```
> 
> (gdb) backtrace
> 
> ```
> 
> 
> 
> and post the output of  the`backtrace`.

Please follow it to provide backtrace logs.

**Comment by uni-manjunath-ke** [comment]
Thanks @csukuangfj 
(gdb) backtrace
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fffafe95859 in __GI_abort () at abort.c:79
#2  0x00007fffb013035a in __cxxabiv1::__terminate (handler=<optimized out>)
    at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#3  0x00007fffb01303c5 in std::terminate ()
    at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#4  0x00007fffb0130658 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7ffff7b39678 <typeinfo for c10::NotImplementedError>, 
    dest=0x7fffe3c06430 <c10::NotImplementedError::~NotImplementedError()>)
    at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#5  0x00007fffe6f0c468 in torch::jit::InterpreterStateImpl::handleError(std::exception const&, bool, c10::NotImplementedError*, c10::optional<std::string>) () from /home/manjunath/anaconda3/envs/sherpa/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so
#6  0x00007fffe6f1a095 in torch::jit::InterpreterStateImpl::runImpl(std::vector<c10::IValue, std::allocator<c10::IValue> >&) ()
   from /home/manjunath/anaconda3/envs/sherpa/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so
#7  0x00007fffe6f0555f in torch::jit::InterpreterState::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) ()
   from /home/manjunath/anaconda3/envs/sherpa/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so
#8  0x00007fffe6ef59ea in torch::jit::GraphExecutorImplBase::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) ()
   from /home/manjunath/anaconda3/envs/sherpa/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so
#9  0x00007fffe6b7d49e in torch::jit::Method::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::string, c10::IValue, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, c10::IValue> > > const&) const () from /home/manjunath/anaconda3/envs/sherpa/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so
#10 0x00007ffff7ccf9b9 in c10::IValue torch::jit::Object::run_method<at::Tensor, at::Tensor>(std::string const&, at::Tensor&&, at::Tensor&&)
    () from ./build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_core.so
#11 0x00007ffff7cce9df in sherpa::OfflineNeMoEncDecCTCModelBPE::Forward(at::Tensor, at::Tensor) ()
   from ./build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_core.so
#12 0x00007ffff7ccec3f in sherpa::OfflineNeMoEncDecCTCModelBPE::WarmUp(at::Tensor, at::Tensor) ()
   from ./build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_core.so
#13 0x00007ffff7f33d1a in sherpa::OfflineRecognizerCtcImpl::WarmUp() ()
   from ./build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_cpp_api.so
#14 0x00007ffff7f32ca2 in sherpa::OfflineRecognizerCtcImpl::OfflineRecognizerCtcImpl(sherpa::OfflineRecognizerConfig const&) ()
   from ./build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_cpp_api.so
--Type <RET> for more, q to quit, c to continue without paging--
#15 0x00007ffff7f3aca0 in std::_MakeUniq<sherpa::OfflineRecognizerCtcImpl>::__single_object std::make_unique<sherpa::OfflineRecognizerCtcImpl, sherpa::OfflineRecognizerConfig const&>(sherpa::OfflineRecognizerConfig const&) ()
   from ./build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_cpp_api.so
#16 0x00007ffff7f270b4 in sherpa::OfflineRecognizer::OfflineRecognizer(sherpa::OfflineRecognizerConfig const&) ()
   from ./build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_cpp_api.so
#17 0x0000555555584e75 in ?? ()
#18 0x00007fffafe97083 in __libc_start_main (main=0x55555558492e, argc=7, argv=0x7fffffffdce8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7fffffffdcd8) at ../csu/libc-start.c:308
#19 0x000055555558450e in ?? ()

**Comment by uni-manjunath-ke** [comment]
Hi @csukuangfj , Pls let us know, if there is an update on this? Thanks

**Comment by uni-manjunath-ke** [comment]
Hi @csukuangfj and @titu1994 , Pls let me know, if there is any update on this? Thanks, Sorry for reposting.

**Comment by csukuangfj** [comment]
> Hi @csukuangfj and @titu1994 , Pls let me know, if there is any update on this? Thanks, Sorry for reposting.

@uni-manjunath-ke 

Sorry for the late reply and thanks for posting the debug info.

It is not clear what bad things happened from the backtrace.

---

Have you tried
https://github.com/k2-fsa/sherpa/pull/332#issuecomment-1463507956
and  does
```
log_probs = model(features, features_len)
print(log_probs.shape)
```
produce any output?

---

Also, are you using the fix from https://github.com/k2-fsa/sherpa/pull/332#issuecomment-1463660502
to export your conformer ctc model? If not, then could you describe how you export your NeMo model via torchscript?

**Comment by uni-manjunath-ke** [comment]
Hi @csukuangfj , 
1. I have tried it and the output is given at:
https://github.com/k2-fsa/sherpa/issues/303#issuecomment-1463754807

2. I am exporting Nemo to torchscript as below: 
m = nemo_asr.models.EncDecCTCModelBPE.from_pretrained('stt_en_conformer_ctc_small')
m.export("model.pt")

And, then using model.pt for decoding with sherpa. Thanks

**Comment by csukuangfj** [comment]
> I am exporting Nemo to torchscript as below:
m = nemo_asr.models.EncDecCTCModelBPE.from_pretrained('stt_en_conformer_ctc_small')
m.export("model.pt")

Have you had any problems with the code above?  I need to change the code of NeMo to get the export working.

Also, are you able to follow
https://k2-fsa.github.io/sherpa/cpp/pretrained_models/offline_ctc/nemo.html#how-to-convert-nemo-models-to-sherpa
to convert the following model
https://k2-fsa.github.io/sherpa/cpp/pretrained_models/offline_ctc/nemo.html#sherpa-nemo-ctc-en-conformer-small-english
to sherpa? Just want to make sure the entire pipeline is working from your side.

**Comment by uni-manjunath-ke** [comment]
Hi @csukuangfj ,

I did not have errors while using export, pls find the logs:
[NeMo I 2023-03-23 09:17:49 mixins:170] Tokenizer SentencePieceTokenizer initialized with 512 tokens
[NeMo W 2023-03-23 09:17:49 modelPT:156] If you intend to do training or fine-tuning, please call the ModelPT.setup_training_data() method and provide a valid configuration file to setup the train data loader.
    Train config : 
    manifest_filepath: /PATH/train_manifest.json
    sample_rate: 16000
    batch_size: 8
    shuffle: true
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
    trim_silence: false
    max_duration: 16
    min_duration: 0.1
    is_tarred: false
    tarred_audio_filepaths: null
    shuffle_n: 2048
    bucketing_strategy: synced_randomized
    bucketing_batch_size: null
    
[NeMo W 2023-03-23 09:17:49 modelPT:163] If you intend to do validation, please call the ModelPT.setup_validation_data() or ModelPT.setup_multiple_validation_data() method and provide a valid configuration file to setup the validation data loader(s). 
    Validation config : 
    manifest_filepath: /PATH/valid_manifest.json
    sample_rate: 16000
    batch_size: 8
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
    
[NeMo W 2023-03-23 09:17:49 modelPT:169] Please call the ModelPT.setup_test_data() or ModelPT.setup_multiple_test_data() method and provide a valid configuration file to setup the test data loader(s).
    Test config : 
    manifest_filepath: /\<path\>/test_manifest.json
    sample_rate: 16000
    batch_size: 8
    shuffle: false
    num_workers: 8
    pin_memory: true
    use_start_end_token: false
    
[NeMo I 2023-03-23 09:17:49 features:267] PADDING: 0
[NeMo I 2023-03-23 09:17:50 save_restore_connector:243] Model EncDecCTCModelBPE was successfully restored from /data/manju/hindi/exp/models/cleaned_tokz_512_hindi_dc_tvs_hdc_tl.nemo.
[NeMo I 2023-03-23 09:17:50 export_utils:398] Swapped 108 modules
[NeMo W 2023-03-23 09:17:51 nemo_logging:349] /home/manjunath/anaconda3/envs/nemo/lib/python3.9/site-packages/nemo/collections/asr/modules/conformer_encoder.py:375: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
      if seq_length > self.max_audio_length:
    
[NeMo W 2023-03-23 09:17:51 nemo_logging:349] /home/manjunath/anaconda3/envs/nemo/lib/python3.9/site-packages/nemo/collections/asr/parts/submodules/multi_head_attention.py:670: UserWarning: __floordiv__ is deprecated, and its behavior will change in a future version of pytorch. It currently rounds toward 0 (like the 'trunc' function NOT 'floor'). This results in incorrect rounding for negative values. To keep the current behavior, use torch.div(a, b, rounding_mode='trunc'), or for actual floor division, use torch.div(a, b, rounding_mode='floor').
      center_pos = self.pe.size(1) // 2 + 1
    
[NeMo I 2023-03-23 09:19:29 exportable:89] Successfully exported EncDecCTCModelBPE to /data/\<path\>/model.pt

**Comment by uni-manjunath-ke** [comment]
Gdb backtrace while running exported model in sherpa is as below:
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
#1  0x00007fffafe95859 in __GI_abort () at abort.c:79
#2  0x00007fffb013035a in __cxxabiv1::__terminate (handler=<optimized out>) at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:48
#3  0x00007fffb01303c5 in std::terminate () at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_terminate.cc:58
#4  0x00007fffb0130658 in __cxxabiv1::__cxa_throw (obj=<optimized out>, tinfo=0x7ffff7b39678 <typeinfo for c10::NotImplementedError>, 
    dest=0x7fffe3c06430 <c10::NotImplementedError::~NotImplementedError()>) at /opt/conda/conda-bld/gcc-compiler_1654084175708/work/gcc/libstdc++-v3/libsupc++/eh_throw.cc:95
#5  0x00007fffe6f0c468 in torch::jit::InterpreterStateImpl::handleError(std::exception const&, bool, c10::NotImplementedError*, c10::optional<std::string>) ()
   from /home/manjunath/anaconda3/envs/sherpa/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so
#6  0x00007fffe6f1a095 in torch::jit::InterpreterStateImpl::runImpl(std::vector<c10::IValue, std::allocator<c10::IValue> >&) ()
   from /home/manjunath/anaconda3/envs/sherpa/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so
#7  0x00007fffe6f0555f in torch::jit::InterpreterState::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) ()
   from /home/manjunath/anaconda3/envs/sherpa/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so
#8  0x00007fffe6ef59ea in torch::jit::GraphExecutorImplBase::run(std::vector<c10::IValue, std::allocator<c10::IValue> >&) ()
   from /home/manjunath/anaconda3/envs/sherpa/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so
#9  0x00007fffe6b7d49e in torch::jit::Method::operator()(std::vector<c10::IValue, std::allocator<c10::IValue> >, std::unordered_map<std::string, c10::IValue, std::hash<std::string>, std::equal_to<std::string>, std::allocator<std::pair<std::string const, c10::IValue> > > const&) const () from /home/manjunath/anaconda3/envs/sherpa/lib/python3.9/site-packages/torch/lib/libtorch_cpu.so
#10 0x00007ffff7ccf9b9 in c10::IValue torch::jit::Object::run_method<at::Tensor, at::Tensor>(std::string const&, at::Tensor&&, at::Tensor&&) ()
   from /mnt/efs/manju/if/tools/sherpa/build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_core.so
#11 0x00007ffff7cce9df in sherpa::OfflineNeMoEncDecCTCModelBPE::Forward(at::Tensor, at::Tensor) ()
   from /mnt/efs/manju/if/tools/sherpa/build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_core.so
#12 0x00007ffff7ccec3f in sherpa::OfflineNeMoEncDecCTCModelBPE::WarmUp(at::Tensor, at::Tensor) ()
   from /mnt/efs/manju/if/tools/sherpa/build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_core.so
#13 0x00007ffff7f33d1a in sherpa::OfflineRecognizerCtcImpl::WarmUp() () from /mnt/efs/manju/if/tools/sherpa/build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_cpp_api.so
#14 0x00007ffff7f32ca2 in sherpa::OfflineRecognizerCtcImpl::OfflineRecognizerCtcImpl(sherpa::OfflineRecognizerConfig const&) ()
   from /mnt/efs/manju/if/tools/sherpa/build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_cpp_api.so
#15 0x00007ffff7f3aca0 in std::_MakeUniq<sherpa::OfflineRecognizerCtcImpl>::__single_object std::make_unique<sherpa::OfflineRecognizerCtcImpl, sherpa::OfflineRecognizerConfig const&>(sherpa::OfflineRecognizerConfig const&) () from /mnt/efs/manju/if/tools/sherpa/build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_cpp_api.so
#16 0x00007ffff7f270b4 in sherpa::OfflineRecognizer::OfflineRecognizer(sherpa::OfflineRecognizerConfig const&) ()
   from /mnt/efs/manju/if/tools/sherpa/build/lib.linux-x86_64-cpython-39/sherpa/lib/libsherpa_cpp_api.so
#17 0x0000555555584e75 in ?? ()
#18 0x00007fffafe97083 in __libc_start_main (main=0x55555558492e, argc=7, argv=0x7fffffffdcd8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdcc8)
    at ../csu/libc-start.c:308
#19 0x000055555558450e in ?? ()

**Comment by uni-manjunath-ke** [comment]
Hi @csukuangfj , If possible could you please try with my models:
Pls download hindi_tl_demo.nemo model from https://huggingface.co/manjunathke/dummy_hindi .  Then convert them to ".pt" & generate tokens.txt file. You can then check those models and we may come to know, if there is an issue.
Pls do not use the hindi_tl_demo.pt & hindi_tokens.txt  from https://huggingface.co/manjunathke/dummy_hindi They are old ones, and in correct.

Thanks
